# NUMBER 1

In [11]:
import numpy as np

rows = int(input("Enter number of rows for random array: "))
cols = int(input("Enter number of columns for random array: "))

X = np.random.rand(rows, cols)

mean_X = X.mean()
std_X = X.std()
X_normalized = (X - mean_X) / std_X

np.save('X_normalized.npy', X_normalized)

print("\nRandom array X:\n", X)
print("\nNormalized array X_normalized:\n", X_normalized)


Enter number of rows for random array (e.g. 5):  5
Enter number of columns for random array (e.g. 5):  5



Random array X:
 [[0.44038656 0.49624243 0.86813137 0.52126619 0.34877697]
 [0.1957022  0.69643076 0.10342956 0.88670922 0.92190907]
 [0.86409291 0.54299967 0.28693123 0.91361763 0.90871235]
 [0.07998498 0.05562754 0.73850377 0.40177101 0.21569305]
 [0.54096146 0.44546766 0.6629826  0.35209478 0.85405356]]

Normalized array X_normalized:
 [[-0.33261125 -0.13351388  1.19207852 -0.04431706 -0.65915221]
 [-1.20478488  0.58005433 -1.53368928  1.258299    1.3837683 ]
 [ 1.17768348  0.03315158 -0.87960043  1.35421359  1.33672879]
 [-1.61725712 -1.70407884  0.73002294 -0.47025578 -1.13352782]
 [ 0.02588641 -0.31449974  0.4608289  -0.64732593  1.14189839]]


# NUMBER 2

In [18]:
A = np.arange(1, 101)**2  # squares of 1..100
A = A.reshape(10, 10)     # 10x10 array

div_by_3 = A[A % 3 == 0]  # numbers divisible by 3

np.save('div_by_3.npy', div_by_3)

print("\nArray A (10x10 squares):\n", A)
print("\nNumbers divisible by 3:\n", div_by_3)


Array A (10x10 squares):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
